name: Deploy to Production
on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: 'deno task build'

      - name: Install deployctl
        run: deno install --global --allow-read --allow-write --allow-env --allow-net --allow-run --no-check -r -f https://deno.land/x/deploy/deployctl.ts

      - name: Upload to Deno Deploy (Production)
        run: deployctl deploy --project=dime-to-dozen --entrypoint=server/main.ts --include=server,dist,deno.json,deno.lock --prod
